(venv) D:\JRUFoundTracker> flask run --host=0.0.0.0 --port=5000
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\JRUFoundTracker\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask\cli.py", line 1129, in main
    cli.main()
    ~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\click\core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\click\core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\click\core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask\cli.py", line 977, in run_command
    raise e from None
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask\cli.py", line 961, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask\cli.py", line 349, in load_app
    app = locate_app(import_name, name)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\main.py", line 1, in <module>
    from app import app
  File "D:\JRUFoundTracker\app.py", line 42, in <module>
    db.create_all()
    ~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5925, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3248, in _run_ddl_visitor
    with self.begin() as conn:
         ~~~~~~~~~~^^
  File "C:\Users\Angelo D. Bonifacio\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3238, in begin
    with self.connect() as conn:
         ~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3274, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3298, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\JRUFoundTracker\venv\Lib\site-packages\pymysql\connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\pymysql\_auth.py", line 267, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "D:\JRUFoundTracker\venv\Lib\site-packages\pymysql\_auth.py", line 144, in sha2_rsa_encrypt
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods